#!/bin/bash

echo "Enter the salary:"
read salary

if [ "$salary" -eq 20000 ]
 then
    tax_percentage=2
elif [ "$salary" -le 20000 ]
 then
    tax_percentage=0
elif [ "$salary" -gt 20000 -a "$salary" -le 40000 ]
 then
    tax_percentage=5
else
    tax_percentage=10
fi

echo "Tax Percentage: $tax_percentage%"


