#!/bin/bash

echo " enter the salary "
read  salary

if [ "$salary" -le 20000 ]
 then
    tax=0  
elif [ $salary  -gt 20000  -a  $salary  -le 40000 ]
 then
    tax=$((salary * 5 / 100)) 
else
    tax=$((salary * 10 / 100)) 
fi

echo "Tax: $tax"

